import { IGem } from "../../core/types";
import red_gem from "../../assets/red_gem.webp";
import green_gem from "../../assets/green_gem.jpg";

export const gems: IGem[] = [
  {
    id: 1,
    rarity: "rare",
    price: 300,
    priceCurrency: "inGame",
    name: "Ruby of Power",
    description: "A ruby that increases power.",
    powerModifier: 15,
    healthModifier: 0,
    gradeModifier: 1,
    removable: true,
    img: red_gem,
  },
  {
    id: 2,
    rarity: "common",
    price: 100,
    priceCurrency: "inGame",
    name: "Sapphire of Health",
    description: "A sapphire that boosts health.",
    powerModifier: 0,
    healthModifier: 10,
    gradeModifier: 0,
    removable: true,
    img: green_gem,
  },
  {
    id: 3,
    rarity: "epic",
    price: 700,
    priceCurrency: "ton",
    name: "Emerald of Fortitude",
    description: "An emerald that greatly enhances both power and health.",
    powerModifier: 20,
    healthModifier: 20,
    gradeModifier: 2,
    removable: false,
    img: green_gem,
  },
  {
    id: 4,
    rarity: "legendary",
    price: 1500,
    priceCurrency: "ton",
    name: "Diamond of Perfection",
    description: "A diamond that significantly boosts all attributes.",
    powerModifier: 30,
    healthModifier: 25,
    gradeModifier: 3,
    removable: true,
    img: green_gem,
  },
  {
    id: 5,
    rarity: "common",
    price: 50,
    priceCurrency: "inGame",
    name: "Amber of Speed",
    description: "An amber that slightly increases power.",
    powerModifier: 5,
    healthModifier: 0,
    gradeModifier: 0,
    removable: true,
    img: green_gem,
  },
];
