import { ICard } from "../../core/types";

export const cards: ICard[] = [
  {
    id: 1,
    rarity: "common",
    price: 100,
    priceCurrency: "inGame",
    name: "Common Sword",
    description: "A basic sword, suitable for new adventurers.",
  },
  {
    id: 2,
    rarity: "rare",
    price: 500,
    priceCurrency: "ton",
    name: "Rare Shield",
    description: "A shield made from rare materials, offering strong defense.",
  },
  {
    id: 3,
    rarity: "legendary",
    price: 1000,
    priceCurrency: "inGame",
    name: "Legendary Bow",
    description: "A bow crafted by the ancient elves, can deal massive damage.",
  },
  {
    id: 4,
    rarity: "epic",
    price: 800,
    priceCurrency: "ton",
    name: "Epic Helmet",
    description:
      "A helmet that grants its wearer enhanced vision and protection.",
  },
  {
    id: 5,
    rarity: "common",
    price: 50,
    priceCurrency: "inGame",
    name: "Healing Potion",
    description: "A potion that heals minor wounds.",
  },
  {
    id: 6,
    rarity: "rare",
    price: 200,
    priceCurrency: "ton",
    name: "Fire Staff",
    description:
      "A staff imbued with the power of fire, casting powerful fireballs.",
  },
  {
    id: 7,
    rarity: "legendary",
    price: 1500,
    priceCurrency: "inGame",
    name: "Phoenix Feather",
    description: "A rare item that can revive you once per day.",
  },
  {
    id: 8,
    rarity: "epic",
    price: 600,
    priceCurrency: "ton",
    name: "Ice Sword",
    description: "A sword made of ice that freezes enemies on impact.",
  },
  {
    id: 9,
    rarity: "common",
    price: 20,
    priceCurrency: "inGame",
    name: "Wooden Shield",
    description: "A basic shield made of wood, useful for beginners.",
  },
  {
    id: 10,
    rarity: "rare",
    price: 350,
    priceCurrency: "ton",
    name: "Golden Ring",
    description: "A golden ring that increases health regeneration.",
  },
  {
    id: 11,
    rarity: "legendary",
    price: 2000,
    priceCurrency: "inGame",
    name: "Dragon Armor",
    description:
      "Armor made from dragon scales, offering unmatched protection.",
  },
  {
    id: 12,
    rarity: "epic",
    price: 900,
    priceCurrency: "ton",
    name: "Lightning Sword",
    description: "A sword that strikes with the power of lightning.",
  },
  {
    id: 13,
    rarity: "common",
    price: 10,
    priceCurrency: "inGame",
    name: "Basic Potion",
    description: "A small potion that restores a little health.",
  },
  {
    id: 14,
    rarity: "rare",
    price: 400,
    priceCurrency: "ton",
    name: "Silver Dagger",
    description:
      "A dagger forged from silver, effective against dark creatures.",
  },
  {
    id: 15,
    rarity: "legendary",
    price: 3000,
    priceCurrency: "inGame",
    name: "Excalibur",
    description: "The legendary sword of kings, capable of defeating any foe.",
  },
  {
    id: 16,
    rarity: "epic",
    price: 1200,
    priceCurrency: "ton",
    name: "Stealth Cloak",
    description: "A cloak that makes its wearer invisible for short periods.",
  },
  {
    id: 17,
    rarity: "common",
    price: 30,
    priceCurrency: "inGame",
    name: "Minor Mana Potion",
    description: "Restores a small amount of mana.",
  },
  {
    id: 18,
    rarity: "rare",
    price: 250,
    priceCurrency: "ton",
    name: "Crystal Ball",
    description: "A ball that allows the user to see into the future.",
  },
  {
    id: 19,
    rarity: "legendary",
    price: 5000,
    priceCurrency: "inGame",
    name: "Sword of the Ancients",
    description: "An ancient sword with the power to vanquish any enemy.",
  },
  {
    id: 20,
    rarity: "epic",
    price: 1100,
    priceCurrency: "ton",
    name: "Wings of the Valkyrie",
    description:
      "Wings that grant the ability to glide and fly for short distances.",
  },
];
