import { Outlet } from "react-router";
import { Box } from "@mui/material";
import { Navigation } from "./components/Navigation/Navigation";
import { useCardStore } from "./core/store/useCardStore";
import zombie from "./assets/zombie_level_1.png";
import { useGemStore } from "./core/store/useGemStore";
import gem1 from "./assets/gem1.png";
import gem2 from "./assets/gem2.png";
import gem3 from "./assets/gem3.png";
import gem4 from "./assets/gem4.png";
import gem5 from "./assets/gem5.png";
import gem6 from "./assets/gem6.png";

export const Layout = () => {
  const setCards = useCardStore((state) => state.setCards);
  const setGems = useGemStore((state) => state.setGems);

  setCards([
    {
      id: 101,
      number: 1,
      rarity: "common",
      price: 100,
      power: 16,
      bonusPower: 0,
      powerCoef: 1.2,
      health: 48,
      bonusHealth: 0,
      healthCoef: 1.2,
      armor: 2,
      bonusArmor: 0,
      armorCoef: 1.6,
      exp: 150,
      level: 1,
      stars: 0,
      fraction: "demons",
      priceCurrency: "inGame",
      name: "Default Zombie",
      description: "A basic tueben'",
      img: zombie,
      gemIds: [],
      sockets: 0,
      element: "simple",
      class: "dd",
    },
    {
      id: 102,
      number: 1,
      rarity: "common",
      price: 100,
      power: 16,
      bonusPower: 0,
      powerCoef: 1.2,
      health: 48,
      bonusHealth: 0,
      healthCoef: 1.3,
      armor: 12,
      bonusArmor: 0,
      armorCoef: 1.5,
      exp: 150,
      level: 1,
      stars: 0,
      fraction: "undead",
      priceCurrency: "inGame",
      name: "Default Zombie",
      description: "A basic tueben'",
      img: zombie,
      gemIds: [],
      sockets: 0,
      element: "poison",
      class: "defender",
    },
    {
      id: 103,
      number: 1,
      rarity: "common",
      price: 100,
      power: 16,
      bonusPower: 0,
      powerCoef: 1.2,
      health: 48,
      bonusHealth: 0,
      healthCoef: 1.3,
      armor: 12,
      bonusArmor: 0,
      armorCoef: 1.5,
      exp: 150,
      level: 1,
      stars: 0,
      fraction: "orcs",
      priceCurrency: "inGame",
      name: "Default Zombie",
      description: "A basic tueben'",
      img: zombie,
      gemIds: [],
      sockets: 0,
      element: "poison",
      class: "dd",
    },
    {
      id: 104,
      number: 1,
      rarity: "common",
      price: 100,
      power: 16,
      bonusPower: 0,
      powerCoef: 1.2,
      health: 48,
      bonusHealth: 0,
      healthCoef: 1.3,
      armor: 12,
      bonusArmor: 0,
      armorCoef: 1.5,
      exp: 150,
      level: 1,
      stars: 0,
      fraction: "elves",
      priceCurrency: "inGame",
      name: "Default Zombie",
      description: "A basic tueben'",
      img: zombie,
      gemIds: [],
      sockets: 0,
      element: "poison",
      class: "defender",
    },
    {
      id: 105,
      number: 1,
      rarity: "common",
      price: 100,
      power: 16,
      bonusPower: 0,
      powerCoef: 1.2,
      health: 48,
      bonusHealth: 0,
      healthCoef: 1.3,
      armor: 12,
      bonusArmor: 0,
      armorCoef: 1.5,
      exp: 150,
      level: 1,
      stars: 0,
      fraction: "alliance",
      priceCurrency: "inGame",
      name: "Default Zombie",
      description: "A basic tueben'",
      img: zombie,
      gemIds: [],
      sockets: 0,
      element: "poison",
      class: "support",
    },
    {
      id: 106,
      number: 1,
      rarity: "common",
      price: 100,
      power: 16,
      bonusPower: 0,
      powerCoef: 1.2,
      health: 48,
      bonusHealth: 0,
      healthCoef: 1.3,
      armor: 12,
      bonusArmor: 0,
      armorCoef: 1.5,
      exp: 150,
      level: 1,
      stars: 0,
      fraction: "undead",
      priceCurrency: "inGame",
      name: "Default Zombie",
      description: "A basic tueben'",
      img: zombie,
      gemIds: [],
      sockets: 0,
      element: "poison",
      class: "support",
    },
  ]);

  setGems([
    {
      id: 120,
      number: 1,
      level: 1,
      inserted: false,
      rarity: "immortal",
      price: 300,
      priceCurrency: "inGame",
      name: "Ruby of Flame Power",
      description: "Ruby increases strength and changes damage type to flame",
      tooltipTitle: "• #+15# attack \n• Changes damage type to flame",
      powerModifier: 15,
      armorModifier: 0,
      healthModifier: 0,
      gradeModifier: 1,
      element: "flame",
      removable: false,
      img: gem6,
    },
    {
      id: 121,
      number: 1,
      level: 1,
      inserted: false,
      rarity: "common",
      price: 100,
      priceCurrency: "inGame",
      name: "Sapphire of Health",
      description: "A sapphire that boosts health.",
      tooltipTitle: "• #+10# health \n• #-20# armor",
      powerModifier: 0,
      armorModifier: -20,
      healthModifier: 10,
      gradeModifier: 0,
      removable: true,
      img: gem2,
      kitId: 1,
    },
    {
      id: 122,
      number: 2,
      level: 1,
      inserted: false,
      rarity: "epic",
      price: 700,
      priceCurrency: "ton",
      name: "Emerald of Fortitude",
      description: "An emerald that greatly enhances both power and health.",
      tooltipTitle: "• #+10# power \n• #+20# health",
      powerModifier: 10,
      armorModifier: 0,
      healthModifier: 20,
      gradeModifier: 2,
      removable: true,
      img: gem3,
      kitId: 1,
    },
    {
      id: 123,
      number: 3,
      level: 1,
      inserted: false,
      rarity: "legendary",
      price: 1500,
      priceCurrency: "ton",
      name: "Diamond of Perfection",
      description: "A diamond that significantly boosts all attributes.",
      tooltipTitle: "• #+45# armor \n• #+25# health",
      powerModifier: 0,
      armorModifier: 45,
      healthModifier: 25,
      gradeModifier: 3,
      removable: true,
      img: gem4,
      kitId: 1,
    },
    {
      id: 124,
      number: 4,
      level: 1,
      inserted: false,
      rarity: "common",
      price: 50,
      priceCurrency: "inGame",
      name: "Amber of Speed",
      description: "An amber that slightly increases power.",
      tooltipTitle: "• #+5# power \n• #+5# armor \n• #+5# health",
      powerModifier: 5,
      armorModifier: 5,
      healthModifier: 5,
      gradeModifier: 0,
      removable: true,
      img: gem5,
    },
    {
      id: 125,
      number: 4,
      level: 1,
      inserted: false,
      rarity: "common",
      price: 50,
      priceCurrency: "inGame",
      name: "Amber of Speed",
      description: "An amber that slightly increases power.",
      tooltipTitle: "• #+5# armor",
      powerModifier: 0,
      armorModifier: 5,
      healthModifier: 0,
      gradeModifier: 0,
      removable: true,
      img: gem1,
    },
  ]);

  return (
    <>
      <Box
        component={"main"}
        sx={{
          position: "relative",
          height: `100vh`,
          width: "100%",
        }}
      >
        <Outlet />
      </Box>
      <Navigation />
    </>
  );
};
