import Bronze from "../../assets/bronze.png";
import Silver from "../../assets/silver.png";
import Gold from "../../assets/gold.png";
import { colors } from "../../core/theme/colors";
import { ICard, IReward } from "../../core/types";
import zombie from "../../assets/zombie_level_1.png";

export const imgByLeague: Record<string, string> = {
  Bronze,
  Silver,
  Gold,
};

export const rewardByLeague: IReward[] = [
  {
    id: 1,
    league: "Bronze",
    reward: "+ 3 000 $GUM",
    rewardValue: 3000,
    rewardColor: colors.common,
    rewardType: "inGame",
    isClaimed: false,
  },
  {
    id: 2,
    league: "Silver",
    reward: "+ 5 000 $GUM",
    rewardValue: 5000,
    rewardColor: colors.common,
    rewardType: "inGame",
    isClaimed: false,
  },
  {
    id: 3,
    league: "Gold",
    reward: "+1 Rare Pack",
    rewardColor: colors.rare,
    rewardType: "pack",
    isClaimed: false,
  },
  {
    id: 4,
    league: "Diamond",
    reward: "20 $NOT",
    rewardColor: colors.legendary,
    rewardType: "not",
    isClaimed: false,
  },
];

export const battleMods = [
  {
    id: 1,
    name: "PVE",
    description: "Challenge the bot and earn",
    energy: 10,
    isAvailable: true,
  },
  {
    id: 2,
    name: "PVP",
    description: "Fight other players and earn",
    energy: 20,
    isAvailable: false,
  },
];

export const PVERounds: Array<{
  id: number;
  name: string;
  reward: number;
  enemyCards: ICard[];
}> = [
  {
    id: 1,
    name: "Level 1",
    reward: 1000,
    enemyCards: [
      {
        id: 1071,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 10,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 100,
        bonusHealth: 0,
        healthCoef: 1.2,
        armor: 5,
        bonusArmor: 0,
        armorCoef: 1.6,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "orcs",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "flame",
        class: "fighter",
      },
      {
        id: 1602,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 10,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 100,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 5,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "orcs",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "poison",
        class: "defender",
      },
      {
        id: 3434,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 10,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 100,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 5,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "orcs",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "flame",
        class: "defender",
      },
    ],
  },
  {
    id: 2,
    name: "Level 2",
    reward: 2000,
    enemyCards: [
      {
        id: 1071,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 16,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 48,
        bonusHealth: 0,
        healthCoef: 1.2,
        armor: 2,
        bonusArmor: 0,
        armorCoef: 1.6,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "demons",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "simple",
        class: "fighter",
      },
      {
        id: 1602,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 16,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 48,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 12,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "undead",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "poison",
        class: "defender",
      },
      {
        id: 3434,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 16,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 48,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 12,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "undead",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "poison",
        class: "defender",
      },
    ],
  },
  {
    id: 3,
    name: "Level 3",
    reward: 3000,
    enemyCards: [
      {
        id: 1071,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 216,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 148,
        bonusHealth: 0,
        healthCoef: 1.2,
        armor: 2,
        bonusArmor: 0,
        armorCoef: 1.6,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "demons",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "simple",
        class: "fighter",
      },
      {
        id: 1602,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 16,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 48,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 12,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "undead",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "poison",
        class: "defender",
      },
      {
        id: 3434,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 16,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 48,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 12,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "undead",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "poison",
        class: "defender",
      },
    ],
  },
  {
    id: 4,
    name: "Level 4",
    reward: 4000,
    enemyCards: [
      {
        id: 1071,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 216,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 148,
        bonusHealth: 0,
        healthCoef: 1.2,
        armor: 2,
        bonusArmor: 0,
        armorCoef: 1.6,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "demons",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "simple",
        class: "fighter",
      },
      {
        id: 1602,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 16,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 48,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 12,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "undead",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "poison",
        class: "defender",
      },
      {
        id: 3434,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 16,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 48,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 12,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "undead",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "poison",
        class: "defender",
      },
    ],
  },
  {
    id: 5,
    name: "Level 5",
    reward: 5000,
    enemyCards: [
      {
        id: 1071,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 216,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 148,
        bonusHealth: 0,
        healthCoef: 1.2,
        armor: 2,
        bonusArmor: 0,
        armorCoef: 1.6,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "demons",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "simple",
        class: "fighter",
      },
      {
        id: 1602,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 16,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 48,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 12,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "undead",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "poison",
        class: "defender",
      },
      {
        id: 3434,
        number: 1,
        rarity: "common",
        tier: "B",
        price: 100,
        damage: 16,
        bonusDamage: 0,
        damageCoef: 1.2,
        health: 48,
        bonusHealth: 0,
        healthCoef: 1.3,
        armor: 12,
        bonusArmor: 0,
        armorCoef: 1.5,
        exp: 150,
        level: 1,
        stars: 0,
        fraction: "undead",
        priceCurrency: "inGame",
        name: "Default Zombie",
        description: "A basic tueben'",
        img: zombie,
        gemIds: [],
        sockets: 0,
        element: "poison",
        class: "defender",
      },
    ],
  },
];
